### ISSUE TITLE
Rust wrapper causes unexpected idx received in HW_RX

### ISSUE THREAD

**Issue by marcfir** [robert-burger/libethercat#5]
Hi Robert,
I am working on a Rust wrapper for libethercat. I am using the `example_with_dc.c` as a reference. The DC example works in C with my demo setup.
Going to Safeop in the Rust wrapper causes unexpected idx received in HW_RX like `HW_RX : received idx 133, but we did not send one?`.

Simply calling the wrapper functions in Rust according to `example_with_dc.c` should result in the same behavior.
Adding some `printf` to send and recv showed that there are multiple packets being sent with the same idx. Is this a timing issue?

If I understand correctly, TX and RX are handled in different threads. The TX in the DC example is handled by the `cyclic_task'.
The `ec_send_distributed_clocks_sync' and `ec_send_process_data' queues datagrams in the tx_high queue which are then sent with `hw_tx'.

The _ecat.rx_ thread is spawned during `ec_open` and checks the `idx` in the datagram on `hw_process_rx_frame`. `tx_send[p_entry_dg->idx]` is set before the actual sending.

**Comment by robert-burger** [comment]
Hi Marc

> Going to Safeop in the Rust wrapper causes unexpected idx received in HW_RX like `HW_RX : received idx 133, but we did not send one?`.

IMHO that should never happen. I usually one get this if there are more than one EtherCAT master instances accidentally sending packets over the same interface.

> Simply calling the wrapper functions in Rust according to `example_with_dc.c` should result in the same behavior. Adding some `printf` to send and recv showed that there are multiple packets being sent with the same idx. Is this a timing issue?

If it is the only processes it might be timing. But i don't get the point because the indices are only reused if they have also been received after the round-trip, or some timeout occurred (which i guess should be very high and usually the packet duration is less than 100us). Do you get some timeout messages? How are the priorities/scheduling of the TX and RX threads?

> If I understand correctly, TX and RX are handled in different threads. The TX in the DC example is handled by the `cyclic_task'. The `ec_send_distributed_clocks_sync' and `ec_send_process_data' queues datagrams in the tx_high queue which are then sent with `hw_tx'.

Yes, that's the case if you are using  the SOCK_RAW interface. If you using one of the hacked drivers ('linux' subfolder) then they can be configure in ethercat polling mode. In this mode the nic does not generate interrupt and after the TX it waits until the frame returned (so there is no RX thread). 

> The _ecat.rx_ thread is spawned during `ec_open` and checks the `idx` in the datagram on `hw_process_rx_frame`. `tx_send[p_entry_dg->idx]` is set before the actual sending.

You mean the RX thread receives a datagram with idx A  before the TX thread marked idx X in the tx_send array? This should not be possible because the frame is filled with datagrams here https://github.com/robert-burger/libethercat/blob/d9c124be9059a71cc81b2941cf2ec3a9b1736b1a/src/hw.c#L297 and marked in tx_send. And this happens before the send done here https://github.com/robert-burger/libethercat/blob/d9c124be9059a71cc81b2941cf2ec3a9b1736b1a/src/hw.c#L283.

Just to mention i have no experience in programming in Rust, but is the wrapper code accessible anywhere?

**Comment by marcfir** [comment]
I found the problem. I missed the 
https://github.com/robert-burger/libethercat/blob/d9c124be9059a71cc81b2941cf2ec3a9b1736b1a/tools/example_with_dc/example_with_dc.c#L91
in the cyclic task. So the thread flooded the network.
